name: Test glayout

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'openfasoc/common/**'
      - 'openfasoc/generators/common/**'
      - 'openfasoc/generators/glayout/**'
  workflow_dispatch:

jobs:
  glayout_sky130:
    strategy:
      matrix:
        component: [nmos, pmos, diff_pair, current_mirror, opamp]

    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          du . -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          du . -h

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test ${{ matrix.component }} component
        env:
          IMAGE_NAME: msaligane/openfasoc:stable
        run: |
          cd $GITHUB_WORKSPACE
          touch glayout.log

          docker run --rm \
            -v $PWD:$PWD \
            -w $PWD \
            $IMAGE_NAME \
            bash -c "\
              pip uninstall glayout -y &&\
              cp ./.github/scripts/test_glayout_ci.py ./openfasoc/generators/glayout/. &&\
              cd ./openfasoc/generators/glayout &&\
              pip3 install --force-reinstall -r requirements.txt &&\
              python3 test_glayout_ci.py --component ${{ matrix.component }}
            " && exit_code=$? | tee -a glayout.log

          if [ $? -ne 0 ]; then exit 1; fi
          if grep "\[ERROR\]" glayout.log; then exit 1; else exit 0; fi