name: sky130hvl_ldo-generator

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  sky130hd_ldoGen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Test sky130hvl LDO
        env:
                IMAGE_NAME: msaligane/openfasoc:stable
        run: |
          cd $GITHUB_WORKSPACE
          touch file.log
          docker run --rm \
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              pip3 install -r requirements.txt &&\
              cd ./openfasoc/generators/ldo-gen &&\
              make sky130hvl_ldo\
            "| tee -a file.log
            if grep "\[ERROR\]" file.log; then exit 1; else exit 0; fi
