name: Tempsense_run

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  sky130hd_temp:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        # with:
        #   ref: topic/GCP
    
      - name: Clone OpenLane repo
        run: |
          cd /tmp
          git clone https://github.com/The-OpenROAD-Project/OpenLane.git

      # - name: Make OpenLane Image
      #   run: |
      #     cd /tmp/OpenLane/docker
      #     make merge

      # Build openlane:current instead of merging
      # `make openlane` applies the current tag to the image
      - name: Make OpenLane image
        run: |
          cd /tmp/OpenLane
          make openlane

      - name: Build PDK
        env:
          PDK_ROOT: /tmp/pdk
          IMAGE_NAME: efabless/openlane:current
        run: |
          cd /tmp/OpenLane
          make pdk
          
      - name: Make Sky130HD Temp
        env:
          PDK_ROOT: /tmp/pdk
          IMAGE_NAME: efabless/openlane:current
        run: |
          docker run --rm\
            -e GITHUB_ACTIONS=1\
            -v /tmp/OpenLane:/openLANE_flow\
            -v $PDK_ROOT:$PDK_ROOT\
            -e PDK_ROOT=$PDK_ROOT\
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              yum install -y time &&\
              cd ./generators/temp-sense-gen &&\
              make sky130hd_temp\
            "
