name: temp_sense_generator

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sky130hd_temp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Build Magic
        run: |
          cd /home/runner/work
          sudo apt-get install m4
          sudo apt-get install tcsh
          sudo apt-get install csh
          sudo apt-get install libx11-dev
          sudo apt-get install tcl-dev tk-dev
          git clone https://github.com/RTimothyEdwards/magic.git
          cd magic
          ./configure
          make
          sudo make install 

      - name: Build the PDK data and test the generator
        run: |
         cd $GITHUB_WORKSPACE
         chmod +x ./.github/scripts/openfasoc_ci/build_pdk.sh
         ./.github/scripts/openfasoc_ci/build_pdk.sh
