name: Test documentation

on:
  pull_request:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install sphinx
      - name: Test documentation
        run: |
          cd docs
          make html
